services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data -port 8147"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8147:8147"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    networks:
      - dynamodb-network

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    container_name: dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb-local:8147
    depends_on:
      - dynamodb-local
    networks:
      - dynamodb-network

networks:
  dynamodb-network:
    driver: bridge